import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./Components/ThemeProvider";
import Footer from "./Components/footer/real_footer";
import Header from "./Components/header/falso_header";
import Menu from "./menu-lateral/page";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">   
        <ThemeProvider>
          <Header />

          <div className="main-layout">
            <Menu />

            <main className="content">
              {children}
              </main>
          </div>

            <Footer />

        </ThemeProvider> 
      </body>
    </html>
  );
}
